'use strict';
angular.module('cm.services')
  .value('teams', [ {name:"ANA", title: "Anaheim Ducks", division: ['Pacific', 'Western'], active:true},
                    {name:"BOS", title: "Boston Bruins", division: ['Atlantic', 'Eastern'], active:true},
                    {name:"BUF", title: "Buffalo Sabres", division: ['Atlantic', 'Eastern'], active:true},
                    {name:"CAR", title: "Carolina Hurricanes", division: ['Pacific', 'Western'], active:true},
                    {name:"CBJ", title: "Columbus Blue Jackets", division: ['Metropolitan', 'Eastern'], active:true},
                    {name:"CGY", title: "Calgary Flames", division: ['Pacific', 'Western'], active:true},
                    {name:"CHI", title: "Chicago Blackhawks", division: ['Central', 'Western'], active:true},
                    {name:"COL", title: "Colorado Avalanche", division: ['Central', 'Western'], active:true},
                    {name:"DAL", title: "Dallas Stars", division: ['Central', 'Western'], active:true},
                    {name:"DET", title: "Detroit Red Wings", division: ['Atlantic', 'Eastern'], active:true},
                    {name:"EDM", title: "Edmonton Oilers", division: ['Pacific', 'Western'], active:true},
                    {name:"FLA", title: "Florida Panthers", division: ['Atlantic', 'Eastern'], active:true},
                    {name:"LAK", title: "Los Angeles Kings", division: ['Pacific', 'Western'], active:true},
                    {name:"MIN", title: "Minnesota Wild", division: ['Central', 'Western'], active:true},
                    {name:"MTL", title: "Montreal Canadiens", division: ['Atlantic', 'Eastern'], active:true},
                    {name:"NJD", title: "New Jersey Devils", division: ['Metropolitan', 'Eastern'], active:true},
                    {name:"NSH", title: "Nashville Predators", division: ['Central', 'Western'], active:true},
                    {name:"NYI", title: "New York Islanders", division: ['Metropolitan', 'Eastern'], active:true},
                    {name:"NYR", title: "New York Rangers", division: ['Metropolitan', 'Eastern'], active:true},
                    {name:"OTT", title: "Ottawa Senators", division: ['Atlantic', 'Eastern'], active:true},
                    {name:"PHI", title: "Philadelphia Flyers", division: ['Metropolitan', 'Eastern'], active:true},
                    {name:"PHX", title: "Phoenix Coyotes", division: ['Pacific', 'Western'], active:true},
                    {name:"PIT", title: "Pittsburgh Penguins", division: ['Metropolitan', 'Eastern'], active:true},
                    {name:"SJS", title: "San Jose Sharks", division: ['Pacific', 'Western'], active:true},
                    {name:"STL", title: "St. Louis Blues", division: ['Central', 'Western'], active:true},
                    {name:"TBL", title: "Tampa Bay Lightning", division: ['Atlantic', 'Eastern'], active:true},
                    {name:"TOR", title: "Toronto Maple Leafs", division: ['Atlantic', 'Eastern'], active:true},
                    {name:"VAN", title: "Vancouver Canucks", division: ['Pacific', 'Western'], active:true},
                    {name:"WPG", title: "Winnipeg Jets", division: ['Central', 'Western'], active:true},
                    {name:"WSH", title: "Washington Capitals", division: ['Metropolitan', 'Eastern'], active:true} ]);
